### PR TITLE
Item seeder

### PR DESCRIPTION
**Pull request by akdelarosa01**
for testing purposes

### CODE REVIEW

**Comment by akdelarosa01** [comment]
Hi sir, I created an Item seeder as you resquested.

**Comment by ylin** [comment]
@akdelarosa01 since you are the only developer let's not use PR to simplify, just commit but tie commits to an issue with a "#<issue number>" format. We will have discuss on the issue itself, which is easier.

**Comment by ylin** [comment]
Strange, when I run seeder it only seeds user data

CleanShot 2023-03-05 at 08 59 43@2x

Even though in my code there are item seeders

CleanShot 2023-03-05 at 09 00 32@2x

**Comment by akdelarosa01** [comment]
Sorry sir I think I didn't register it from the whole seeder call function,

Please command

php artisan db:seed ItemSeeder

**Comment by akdelarosa01** [comment]
Hi sir,
you can adjust the memory_limit in php.ini file
Please check this link
https://www.groovypost.com/howto/howto/how-to-solve-php-fatal-error-allowed-memory-size-of-8388608-bytes-exhausted/

**Comment by ylin** [comment]
I get error 

CleanShot 2023-03-17 at 15 34 04@2x

`Data too long for column 'std_material_used' at row 1`

It's because in migration for Item

`$table->string('std_material_used')->length(20)->nullable(); //P`

20 is too small for the length in the seeder

Should increase? 

Also in ItemSeeder, should add this line? 

`use App\Models\Item;`

Otherwise get this error on migration

CleanShot 2023-03-17 at 15 36 31@2x

**Comment by akdelarosa01** [comment]
Hi sir, please see this pull request #13

**Pull request merged**
